/**
 * Created by Administrator on 2018/1/15.
 */
(function(){
    angular.module('app',['ui.router','app.controller','app.service','app.directive','app.filter'])
        .config(function($stateProvider,$urlRouterProvider){
            $urlRouterProvider.otherwise('/home');

            $stateProvider
                .state('home',{
                    url:'/home',
                    templateUrl:'view/home.html',
                    controller:'homeController'
                })
                .state('food',{
                    url:'/food',
                    templateUrl:'view/food.html',
                    controller:'foodController'
                })
                .state('addFood',{
                    url:'/addFood',
                    templateUrl:'view/addFood.html',
                    controller:'addFoodController'
                })
                .state('editFood',{
                    url:'/editFood?foodId',
                    templateUrl:'view/editFood.html',
                    controller:'editFoodController'
                })
                .state('addHealthy',{
                    url:'/addHealthy',
                    templateUrl:'view/addHealthy.html',
                    controller:'addHealthyController'
                })
                .state('editHealthy',{
                    url:'/editHealthy?healthyId',
                    templateUrl:'view/editHealthy.html',
                    controller:'editHealthyController'
                })
                .state('section',{
                    url:'/section',
                    templateUrl:'view/section.html',
                    controller:'sectionController'
                })
                .state('menu',{
                    url:'/menu',
                    templateUrl:'view/menu.html',
                    controller:'menuController'
                })
                .state('addMenu',{
                    url:'/addMenu',
                    templateUrl:'view/addMenu.html',
                    controller:'addMenuController'
                })
                .state('editMenu',{
                    url:'/editMenu?menuId',
                    templateUrl:'view/editMenu.html',
                    controller:'editMenuController'
                })
                .state('healthy',{
                    url:'/healthy',
                    templateUrl:'view/healthy.html',
                    controller:'healthyController'
                })
                .state('invitation',{
                    url:'/invitation',
                    templateUrl:'view/invitation.html',
                    controller:'invitationController'
                })
                .state('addInvitation',{
                    url:'/addInvitation',
                    templateUrl:'view/addInvitation.html',
                    controller:'addInvitationController'
                })
                .state('checkInvitation',{
                    url:'/checkInvitation?invitationId',
                    templateUrl:'view/checkInvitation.html',
                    controller:'checkInvitationController'
                });
        });

}());
